name: Build and Deploy

on:
  push:
    branches:
      - develop

env:
  AZURE_WEBAPP_NAME: CodyzeVSPlugin.sln
  AZURE_WEBAPP_PACKAGE_PATH: 'published'      # set this to the path to your web app project, defaults to the repository root

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
      with:
        vs-version: "[16.4,16.6)"
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore ${{ env.AZURE_WEBAPP_NAME }}

    - name: Build
      run: msbuild ${{ env.AZURE_WEBAPP_NAME }} /p:Configuration=Release

    - name: Publish artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: codyze-plugin
        path: CodyzeVSPlugin\bin\Release\CodyzeVSPlugin.vsix
